#!/usr/bin/env python3
# requires: python3
"""Regenerate site/themes.js from the desktop's own palette file.

The landing page wears the same eleven palettes the desktop does, and gets them
from the same place: setup/dotfiles/.chezmoidata/themes.toml. Copying the
colours into the page by hand is exactly the drift this repository keeps
finding, one surface further out - so the page's copy is generated, and this is
what generates it.

Run it after adding or changing a theme:

    ./tools/site-themes.py

checks/manual.sh has no opinion about the site, so nothing fails if this is not
re-run; the page simply keeps showing the palette it was built with. Re-run it.
"""

import json
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "setup" / "dotfiles" / ".chezmoidata" / "themes.toml"
TARGET = REPO / "site" / "themes.js"

# The roles the page actually paints with. Every theme must define all of them
# (the desktop enforces that too - see checks/session.sh), so a missing one is a
# real problem rather than something to paper over with a default.
ROLES = [
    "bg", "bar", "surface", "surface_alt", "text", "muted",
    "accent", "secondary", "tertiary", "ok", "warning", "urgent",
]


def main() -> int:
    with SOURCE.open("rb") as fh:
        data = tomllib.load(fh)

    themes = []
    for name, theme in data["themes"].items():
        missing = [role for role in ROLES if role not in theme]
        if missing:
            print(f"FAIL {name}: missing {', '.join(missing)}", file=sys.stderr)
            return 1
        entry = {
            "name": name,
            "description": theme.get("description", ""),
            "mode": theme.get("mode", "dark"),
        }
        entry.update({role: theme[role] for role in ROLES})
        themes.append(entry)

    payload = {"default": data.get("theme", "neon"), "themes": themes}

    TARGET.write_text(
        "// Generated by tools/site-themes.py from\n"
        "// setup/dotfiles/.chezmoidata/themes.toml - do not edit by hand.\n"
        "window.SWAYSTONE = " + json.dumps(payload, indent=2) + ";\n"
    )
    print(f"wrote {TARGET.relative_to(REPO)} ({len(themes)} themes, default {payload['default']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
